name: 💡 Product backlog item
description: New development step
title: "[PBI] <title>"
labels: []
body:
- type: textarea
  attributes:
    label: Description 
    description: Add a description...
    Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false